services:
  odoo:
    image: odoo:18.0
    depends_on:
      - db
    env_file: .env
    restart: always
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./logs:/var/log/odoo
    networks:
      - odoo-net

  db:
    image: postgres:15
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgres-config/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - odoo-net

  nginx:
    image: nginx:stable
    depends_on:
      - odoo
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/var/www/certbot
      - ./nginx/ssl:/etc/letsencrypt
    networks:
      - odoo-net

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/html:/var/www/certbot
    # Este entrypoint es para la RENOVACIÓN automática cada 12 horas.
    # Para emitir el primer certificado usa:
    #   docker compose run --rm --entrypoint certbot certbot \
    #     certonly --webroot -w /var/www/certbot \
    #     -d chefalitas.com.do -d www.chefalitas.com.do ...
    entrypoint: >
      /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h; done"
    networks:
      - odoo-net

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    env_file: .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - odoo-net

networks:
  odoo-net:
    driver: bridge

volumes:
  odoo-data:
  postgres-data:
  pgadmin-data:
