services:
  odoo:
    image: odoo:18.0
    depends_on:
      - db
    env_file: .env
    restart: always
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./logs:/var/log/odoo
    networks:
      - odoo-net
    # >>> Más prioridad y más recursos <<<
    cpu_shares: 2048      # prioridad alta de CPU frente a otros
    cpus: "2.0"           # puede usar hasta 2 cores lógicos
    mem_reservation: 2g   # el sistema intenta reservarle 2 GB
    mem_limit: 3g         # no puede pasar de 3 GB

  db:
    image: postgres:15
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgres-config/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - odoo-net
    # >>> Base de datos también prioritaria <<<
    cpu_shares: 2048
    cpus: "1.5"
    mem_reservation: 2g
    mem_limit: 3g

  nginx:
    image: nginx:stable
    depends_on:
      - odoo
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/var/www/certbot
      - ./nginx/ssl:/etc/letsencrypt
    networks:
      - odoo-net
    # >>> Menos prioridad que odoo/db, pero sin ahogarlo <<<
    cpu_shares: 512
    cpus: "0.5"
    mem_limit: 512m

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/html:/var/www/certbot
    entrypoint: >
      /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h; done"
    networks:
      - odoo-net
    # >>> Muy bajo consumo, no hace falta mucho <<<
    cpu_shares: 256
    cpus: "0.25"
    mem_limit: 256m

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:5050"
    env_file: .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - odoo-net
    # >>> Menos importante que odoo/db y nginx <<<
    cpu_shares: 128
    cpus: "0.25"
    mem_limit: 256m

networks:
  odoo-net:
    driver: bridge

volumes:
  odoo-data:
  postgres-data:
  pgadmin-data:
